# https://rust-lang.github.io/rustfmt/?version=v2.0.0-rc.2
condense_wildcard_suffixes = true
error_on_line_overflow = true
style_edition = "2024"
fn_single_line = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
hex_literal_case = "Lower"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
imports_granularity = "One"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
