name: Action
on:
    push:
        paths-ignore:
            - '.github/workflows/*'
    pull_request:
    workflow_dispatch:

jobs:
    cargo_check:
        name: Cargo Check
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{matrix.os}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Rust Download
              uses: actions-rust-lang/setup-rust-toolchain@v1
            - name: Check
              run: cargo check --verbose --release

    cargo_clippy:
        name: Cargo Clippy
        needs: cargo_check
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{matrix.os}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Rust Download
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                components: clippy
            - name: Cargo clippy
              run: cargo clippy

    cargo_fmt:
        name: Cargo fmt
        needs: cargo_check
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{matrix.os}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Rust install
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                toolchain: nightly
                components: rustfmt
            - name: Cargo fmt
              run: cargo +nightly fmt --all -- --check

    cargo_build:
        name: Cargo Build
        needs: [cargo_fmt, cargo_clippy]
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{matrix.os}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Rust Download
              uses: actions-rust-lang/setup-rust-toolchain@v1
            - name: Cargo Build
              run: cargo build

    cargo_test:
        name: Cargo test
        needs: cargo_build
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Git checkout
              uses: actions/checkout@v4
            - name: Rust install
              uses: actions-rust-lang/setup-rust-toolchain@v1
            - name: Cargo test
              run: cargo test
